### ISSUE TITLE
Товар (Product)

### ISSUE THREAD

**Issue by mindesik** [milaxcom/mconsole-commerce#7]
Создать модель базового продукта
- `integer` product_id
- ~~`integer` category_id~~
- `string` article
- `string` slug
- `string` name
-  `text` description
- `text` tables
- `text` lists
- `integer` price
- `integer` discount_price
- `integer` increase_price
- `integer` decrease_price
- `integer` quantity
- `boolean` enabled

А так же включить трейты для обложки и галлереи

**Comment by rudenko-v** [comment]
Добавать связь товар к товару (product_id)

**Comment by mindesik** [comment]
Записано
